fix(concourse): Calculate image tag as part of pipeline instead of during pipeline set.
- Fixes inconsistent tags being used for images.

diff --git a/concourse/ci.yml b/concourse/ci.yml
--- a/concourse/ci.yml
+++ b/concourse/ci.yml
@@ -21,6 +21,8 @@ resources:
       access_token: ((github_access_token))
   - name: github-release-tag
     type: key-value
+    source:
+      file: tag-output/tag
 
 # Define the common terraform task as an anchor
 terraform-task: &terraform-task
@@ -34,19 +36,24 @@ terraform-task: &terraform-task
         repository: hashicorp/terraform
     inputs:
       - name: resource-repo
+      - name: github-release-tag
     params:
       secrets: ((sdp_((env))_digital_landscape_secrets))
       github_access_token: ((github_access_token))
-      tag: ((tag))
+      env: ((env))
     run:
       path: sh
       args:
         - -cx
         - |
           echo "DEBUG: Environment is ${env}"
-          echo "DEBUG: Tag is ${tag}: ((tag))"
+          echo "DEBUG: Tag is ${tag}"
+          export tag=$(cat github-release-tag/tag)
+          if [[ "$env" == "prod" ]] && [[ "$branch" != "main" && "$branch" != "master" ]]; then
+            echo "Not on main branch, skipping terraform for prod."
+            exit 0
+          fi
           apk add --no-cache jq curl
-          export tag=((tag))
           if [[ "$env" == "prod" && ! "$tag" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
             echo "ERROR: Tag '$tag' is not in semantic versioning format (vX.Y.Z)"
             exit 1
@@ -56,11 +63,57 @@ terraform-task: &terraform-task
     timeout: 30m
 
 jobs:
+  - name: calculate-tag
+    public: true
+    plan:
+      - get: github-release
+        trigger: true
+      - get: resource-repo
+        trigger: false
+      - task: calculate-tag
+        config:
+          platform: linux
+          image_resource:
+            type: docker-image
+            source:
+              repository: alpine
+          inputs:
+            - name: resource-repo
+            - name: github-release
+          outputs:
+            - name: tag-output # Output directory for the tag
+          params:
+            branch: ((branch))
+          run:
+            path: sh
+            args:
+              - -cx
+              - |
+                apk add --no-cache git
+                echo "Calculating tag for branch: ${branch}"
+                if [[ "$branch" == "main" || "$branch" == "master" ]]; then
+                  # Get the latest tag that matches the format vX.Y.Z
+                  tag=$(git -C resource-repo tag --list 'v[0-9]*.[0-9]*.[0-9]*' | sort -V | tail -n 1)
+                  if [[ -z "$tag" ]]; then
+                    echo "No valid semantic versioning tags (vX.Y.Z) found. Cannot set pipeline."
+                    exit 1
+                  fi
+                else
+                  # Remove non-alphanumeric characters and take the first 7 characters
+                  tag=$(echo "${branch}" | tr -cd '[:alnum:]' | cut -c1-7)
+                fi
+                echo "Calculated tag: ${tag}"
+                # Write the tag to a file for output
+                echo "${tag}" > tag-output/tag
+      - put: github-release-tag
+        params:
+          directory: tag-output
 
   - name: deploy-after-github-release-dev
     public: true
     plan:
-      - get: github-release
+      - get: github-release-tag
+        passed: [calculate-tag]
         trigger: true
       - get: resource-repo
         trigger: false
@@ -74,15 +127,13 @@ jobs:
               repository: hashicorp/terraform
           inputs:
             - name: resource-repo
-            - name: github-release
-          outputs:
-            - name: release-tag-output # Output directory for the tag
+            - name: github-release-tag
           params:
             aws_account_id: ((aws_account_sdp_dev))
             aws_role_arn: arn:aws:iam::((aws_account_sdp_dev)):role/sdp-concourse-dev
             secrets: ((sdp_dev_digital_landscape_secrets))
             env: dev
-            tag: github-release/tag # Use the release tag from the resource
+            tag: github-release-tag/tag # Use the release tag from the resource
             repo_name: ((repo_name))
           run:
             path: sh
@@ -91,7 +142,7 @@ jobs:
               - |
                 apk add --no-cache aws-cli podman jq iptables curl
                 export repo_name=((repo_name))
-                export tag=$(cat github-release/tag)
+                export tag=$(cat github-release-tag/tag)
                 # Write the tag to a file for output
                 echo "${tag}" > release-tag-output/tag
                 echo "Using tag: ${tag}"
@@ -100,15 +151,10 @@ jobs:
                 source ./resource-repo/concourse/scripts/assume_role.sh
                 ./resource-repo/concourse/scripts/build_image.sh
         timeout: 15m
-      - put: github-release-tag
-        params:
-          directory: release-tag-output
       - <<: *terraform-task
         params:
           github_access_token: ((github_access_token))
           env: dev
-          # tag: github-release/tag
-          tag: ((tag))
           secrets: ((sdp_dev_digital_landscape_secrets))
 
   - name: release-build-and-push-prod
@@ -161,5 +207,4 @@ jobs:
         params:
           github_access_token: ((github_access_token))
           env: prod
-          tag: release-tag-output/tag
           secrets: ((sdp_prod_digital_landscape_secrets))
